### ISSUE TITLE
User Workflow Design [ 10 hours ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/TEKDB#1]
PDF or other visual representation of site workflow for a user browsing for 1-2 resources given 1-2 constraints.

Preferably an interactive PDF generated by Balsamiq 

* [x] log in (as user)
* [x] Home/Landing page
* [x] Open Search ('search all' or 'search [resource type]' or both...)
* [x] Fill out Form
* [x] View results
* [x] Expand result
* [x] Print/Export

**Comment by rhodges** [comment]
for action 3 "Open Search" - let's try to design a 'search all' (with options to restrict results to type if desired). However, we have to be sure we support all search types and needs we can derive from the existing tool

**Comment by pollardld** [comment]
[admin.pdf](https://github.com/Ecotrust/TEKDB/files/800699/admin.pdf)
[TEK.pdf](https://github.com/Ecotrust/TEKDB/files/800698/TEK.pdf)
[user.pdf](https://github.com/Ecotrust/TEKDB/files/800697/user.pdf)

**Comment by pollardld** [comment]
additional edits from Megan:  

- [ ] remove resource to resource relationship on admin flow. no species relationships needed
- [ ] remove any locality references no need from locality 
- [ ] add annotation for admin uses
- [ ] add annotation for user uses
- [ ] add link to relationships in search relationships form
- [ ] relationship all data
- [ ] add button for remove
- [ ] add user button for print and export 
    - all
    - each entry
    - export needs only be text

**Comment by rhodges** [comment]
@pollardld  Is this ready to be closed?
